apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: invalid-vm
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
        resources:
          requests:
            memory: 512Mi
      volumes:
        - name: containerdisk
          containerDisk:
            image: this-image/does-not-exist:latest
